### ISSUE TITLE
Grabber

### ISSUE THREAD

**Issue by Prince123aj** [AxZeRxD/Thallium-Nuker#5]
.

**Comment by AxZeRxD** [comment]
> .

Join https://discord.gg/coderz 
And proof it kiddo 
It is a grabber ? 
I hope you have a proof else fuck your self kiddo 
Rn niggas 
Edited . From "LUND HAI YE "
SUS KIDDO

**Comment by Princepapa** [comment]
Lodu grabber daldega sab me 😂

**Comment by AxZeRxD** [comment]
proof it kiddo
